name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
             echo "Hello World"
             echo "Second output"
      - name: Print greeting World
        run: echo "Hello World"
      - name: Print goodbye
        run: echo "Bye"
    
